# 200 hours training configuration (using available 200h subset)
experiment_name: "whisper-large-v3-kin-200h"
run_training: true
dataset_subset: "audio_200h"  # Use the 20h subset from evie-8/kinyarwanda-speech-hackathon
use_wandb: false
use_mlflow: true
seed: 42