# 1 hour Shona training configuration
experiment_name: "whisper-large-v3-shona-1h"
run_training: true
dataset_name: "evie-8/afrivoices"
dataset_subset: "sna"  # Shona subset
language_code: "sna"
target_hours: 1
use_wandb: false
use_mlflow: true
seed: 42