# 1 hour training configuration (using closest available subset)
experiment_name: "whisper-large-v3-kin-1h"
run_training: true  # Enable training
dataset_subset: "audio_1h"  # Use the 1h subset from evie-8/kinyarwanda-speech-hackathon
use_wandb: false
use_mlflow: true
seed: 42